# Generated by Django 3.1.2 on 2021-05-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210503_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
