# Generated by Django 3.1.2 on 2021-05-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_tag_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='main',
        ),
        migrations.AddField(
            model_name='tagarticle',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
