# Generated by Django 3.1.2 on 2021-05-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210503_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='scopes', through='articles.TagArticle', to='articles.Article'),
        ),
    ]
