# Generated by Django 3.1.2 on 2021-05-03 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20210503_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagarticle',
            name='main',
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(related_name='scopes', through='articles.TagArticle', to='articles.Article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='tagarticle',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='tagarticle',
            name='scopes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag', verbose_name='Раздел'),
        ),
    ]
