# Generated by Django 3.1.2 on 2021-05-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210503_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
