# Generated by Django 3.1.2 on 2021-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_tagarticle_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagarticle',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
