# Generated by Django 3.1.2 on 2021-05-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_tagarticle_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagarticle',
            name='is_main',
        ),
    ]
