# Generated by Django 3.1.2 on 2021-05-03 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20210503_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['topic'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='is_main',
        ),
    ]
